#pragma config(Sensor, dgtl1,  cin1,           sensorDigitalIn)
#pragma config(Sensor, dgtl2,  cin2,           sensorDigitalIn)
#pragma config(Sensor, dgtl3,  ,               sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true)
	{
		if(SensorValue[cin1])
			SensorValue[dgtl3] = 1;

	}

}
