#pragma config(Motor,  port1,           lift,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void changeFloors(int currentFloor, int wantedFloor)
{
	if(currentFloor<wantedFloor)
	{

	}
	else if(currentFloor>wantedFloor)
	{

	}
	else
	{

	}
}

int call()
{

	return wantedFloor;
}

int floorValue(
task main()
{



}
