#pragma config(Sensor, dgtl1,  cout1,          sensorDigitalOut)
#pragma config(Sensor, dgtl2,  cout2,          sensorDigitalOut)
#pragma config(Sensor, dgtl3,  ,               sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		SensorValue[cout1] = 1;
		if(SensorValue[cout1]) SensorValue[dgtl3] = 1;
	}
}
