#pragma config(Sensor, dgtl1,  cout1,          sensorDigitalOut)
#pragma config(Sensor, dgtl2,  cout2,          sensorDigitalOut)
#pragma config(Sensor, dgtl3,  cout3,          sensorDigitalOut)
#pragma config(Sensor, dgtl4,  cin1,           sensorDigitalIn)
#pragma config(Sensor, dgtl5,  led1,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  led2,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  led3,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  led4,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  led5,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, led6,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, led7,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, led8,           sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int ledArray[] = {led1, led2, led3, led4, led5, led6, led7, led8};

void requestButtonState(int index)
{
	switch(index)
	{
		case 0:
			SensorValue[cout1] = 0;
			SensorValue[cout2] = 0;
			SensorValue[cout3] = 0;
			break;
		case 1:
			SensorValue[cout1] = 0;
			SensorValue[cout2] = 0;
			SensorValue[cout3] = 1;
			break;
		case 2:
			SensorValue[cout1] = 0;
			SensorValue[cout2] = 1;
			SensorValue[cout3] = 0;
			break;
		case 3:
			SensorValue[cout1] = 0;
			SensorValue[cout2] = 1;
			SensorValue[cout3] = 1;
			break;
		case 4:
			SensorValue[cout1] = 1;
			SensorValue[cout2] = 0;
			SensorValue[cout3] = 0;
			break;
		case 5:
			SensorValue[cout1] = 1;
			SensorValue[cout2] = 0;
			SensorValue[cout3] = 1;
			break;
		case 6:
			SensorValue[cout1] = 1;
			SensorValue[cout2] = 1;
			SensorValue[cout3] = 0;
			break;
		case 7:
			SensorValue[cout1] = 1;
			SensorValue[cout2] = 1;
			SensorValue[cout3] = 1;
			break;
	}
}


task main()
{
	while(true)
	{
	  for(int i=0; i<8; i++)
	  {
		  requestButtonState(i);
		  wait1Msec(5);
	    SensorValue[ledArray[i]] = SensorValue[cin1];
	  }
	}
}
